### PR TITLE
Numeric Goals/Type Selector and Increment Gesture

### PR DESCRIPTION
**Pull request by jakedp7**
Not sure if you're taking PRs for the hidden numeric goals functionality, but I made some modifications for my own use and wanted to at least let the maintainers decide.

Summary of changes:
- Got rid of the habit type dialog upon habit creation, to clean up the interface a bit. Instead, the habit type is selected by a spinner in the habit editor dialog. 
- Implemented GestureDetector in NumberButtonView. A single tap increments the count of a numeric habit, a double tap decrements it, and press-and-hold works as it did (brings up the value selection dialog).

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the pull request, @jakedp7. I will have a closer look, but, to justify why the app is currently the way it is:

i) As discussed in #42, I am planning to include other types of numerical/categorical habits. At some point, we will need to explain to the user more clearly how do these types differ, and perhaps show them examples of each habit. I was planning to do this in the habit type dialog. Besides, adding new habits is not something that users will do every day, so I am okay with this operation having some extra steps.

ii) If the user has activated the "toggle habits with short press" option, then a single tap should bring up the value selection dialog. I'm aware that it would be very useful to have a quick shortcut to increment/decrement the value, but we also need to worry about accidental data entry. I'm not sure what the best solution would be.

**Comment by jakedp7** [comment]
Alright @iSoron, thanks for the feedback - I'll go ahead and close this then.

**Comment by iSoron** [comment]
I agree that #42 is too broad. I am planning to create more specific issues soon. In the meanwhile, these are some areas I'd like to see improved before numerical habits become available to all users:

- [ ] Make widgets work with numerical habits (in particular, the CheckmarkWidget)
- [ ] Make notifications actions work with numerical habits
- [ ] Fix streak calculation (number of consecutive days above the threshold)
- [ ] Implement conversion between types (yes/no to numerical, and vice-versa)
- [ ] Update the tasker plugin

Let me know if you would like to work on anything here, or if you have any questions.

**Comment by jakedp7** [comment]
@iSoron I'd love to help. Is there a better venue to talk about it in? I'm not a part of the Slack mentioned in the Wiki.

**Comment by iSoron** [comment]
@jakedp7 The Slack channel was not very active, and it was behind closed doors, so I shut it down. If you would like to discuss a new feature, please feel free to open an issue or submit a pull request. In this way, others can join the discussion too.

**Pull request closed without merging**
