### PR TITLE
Update EditText of Edit Habit to capitalize sentences

### PR DESCRIPTION
**Pull request by vanniktech**
Basically when entering a word the first letter will be capitalized. Something minor that bugs me always a bit.

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the patch. Could you also add that attribute to the question field? I will merge it then.

**Comment by vanniktech** [comment]
@iSoron can I do this in another PR? (was too lazy to checkout the project) I did this one via the web interface and I don't know how to squash commits from here. Or proceed editing more files and committing them again.

**Comment by iSoron** [comment]
Sure. Not a problem.

**Comment by vanniktech** [comment]
There you go #33

**Pull request merged**
