### PR TITLE
Fix for issue #168

### PR DESCRIPTION
**Pull request by regularcoder**

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the patch. I don't think we need the field `habitNotFound`. You are essentially using it to return an extra value whenever `getHabitFromWidgetId` throws an exception. The same could be achieved with a custom exception. You would need to:

1. Make `getHabitFromWidgetId` throw a more specific exception, say `HabitNotFoundException`. You would have to create this exception. It could go into the package `org.isoron.uhabits.models`.
2. Make the function `drawErrorWidget` receive an exception as parameter. If the exception is an instance of `HabitNotFoundException`, then it shows the "not found" message. Otherwise, it shows the generic one.

**Comment by regularcoder** [comment]
Thanks for reviewing. I agree that a custom exception approach is better. Will revise and resubmit.

**Comment by regularcoder** [comment]
Updated to use a custom exception instead of a flag. Please can you review again?

I inherited from RuntimeException for the sake of simplicity.

**Comment by iSoron** [comment]
Looks good. I have merged it. Thank you for the patch.

**Pull request merged**
