### PR TITLE
StackView Widgets (#45)

### PR DESCRIPTION
**Pull request by vyu1**
I enjoy using the checkmark widget and really like it's transparent design, but having 5-7 checkmark widgets takes up way too much screen space on my home screen. I implemented a StackView style for the existing Checkmark widget. This new feature is related to https://github.com/iSoron/uhabits/issues/45.
To test my changes, place down a checkmark widget and a new `HabitPicker` dialog should appear. This dialog allows you to select up to as many habits as you prefer. If you only select 1, then the app will create the familiar Checkmark widget we have today. If you select multiple, then the app creates a StackView-style Checkmark widget in which you can scroll through the specific habits you selected.
There are a few things to be discussed:
1. All the widgets themes are opaque right now instead of transparent. I'm not really sure how I can change the Context theme for just the StackView-styled Checkmark widget.
2. I left a TODO comment in the code about this one. If the adapter for the StackView is empty or hasn't been retrieved by the OS, an "empty view" appears as a placeholder. Right now, the empty view consists of just a TextView that says, "Checkmark Stack Widget."

I would love any and all feedback!

### CODE REVIEW

**Comment by iSoron** [comment]
Hi Victor, thank you for the pull request! I think this is a great feature. The StackView worked even better than I expected. I have been testing this on the emulator and I came across two glitches:

1. When the user clicks a widget, sometimes the entire stackview disappears for a second and is replaced by a loading text. See the screen capture below. Do you know what might be causing this, and have you tried to fix it? I can have a look into it myself if you would like.

2. When the user adds two stacks of checkmark buttons, they both end up with the same cards. Even if the widget is first removed and then re-added, it seems like habits that were selected for the first stack still show up.

device

**Comment by vyu1** [comment]
@iSoron Details of the changes I just pushed:
1. At the time you tested this new feature, I allowed the user to pick which habits they wanted in their stack-view widget. You pointed out an error with this feature (the 2nd glitch you commented above with). I realized that this feature will not be possible. The method `setRemoteAdapter` updates any widgets with the same layout all exactly the same way. If you look in the `RemoteViews` API, you can see that there is a `setRemoteAdapter` method that _can_ set the adapter for widgets individually, but it's deprecated and, if used, will simply ignore the value of the widget id we pass it.
2. I think I made a pretty cool change since last time, which was supporting the "stack view" widget design for _all_ the widget types we have now! To test, place down a home screen widget, click the new "create a stack view widget" button at the top of the dialog that opens up, and you should see a stack view widget for any widget type you choose.
3. Lastly, I have actually spent most of my time trying to fix glitch #1 you mentioned above, but have not been able to fix it. I think the "flash" that we see is because `onDataSetChanged()` is being called in `StackWidgetService`.
Please let me know what you think of these points!

**Comment by iSoron** [comment]
Hi @vyu1, sorry about the long delay. I finally had some time to work on this, and I was able to reduce the flicker problem considerably. It's not perfect, but I think it's good enough. I went ahead and merged your patches into the `dev` branch. Thank you a lot for your help; I'm sure the users will also appreciate it. Also, please let me know if you would like to work on anything else.

**Comment by vyu1** [comment]
Hey @iSoron, sorry I haven't responded to this message in over a month!! I'm so excited to hear this has been merged in and I appreciate your thanks! Hopefully I can find another thing to work on and contribute to, thanks again 😄

**Pull request merged**
