### PR TITLE
Remove use of static context from HabitsApplication class

### PR DESCRIPTION
**Pull request by AnirudhaAgashe**
removed static context from application class. Replaced static method to obtain context with appropriate dependency

### CODE REVIEW

**Comment by AnirudhaAgashe** [comment]
I have closed the issue #222 and generated a pull request with the changes that were needed to remove the static context.

**Comment by iSoron** [comment]
Hi @AnirudhaAgashe, sorry about the long delay. I have been busy recently, but I will review your pull request shortly. Thank you for sending it.

**Comment by iSoron** [comment]
Hi @AnirudhaAgashe, thank you again for the pull request. I agree with the removal of the static method `getContext()` from the class `HabitsApplication`.

I would like to keep the code inside the controllers completely Android-free. That is, to instantiate a controller, we shouldn't need a context. I see you currently use the context when calling `exportCSVFactory.create(context, selected, ...)`. This can be avoided by modifying the constructor of `ExportCSVTask`. If you write it like this:
```
public ExportCSVTask(@Provided @AppContext Context context,
                     @Provided @NonNull HabitList habitList,
                     @NonNull List<Habit> selectedHabits,
                     @NonNull Listener listener)
```
then AutoFactory will automatically find a reference to the context for us. Then, on the controller, you can just call `exportCSVFactory.create(selected, ...)`. The class `ExportDBTask` can also be modified to use AutoFactory, just like ExportCSVTask, so we don't need a reference to the context. Please, let me know if you need any help doing this.

Other than that, please add either `@Nullable` or `@NonNull` to every method parameter.

**Comment by AnirudhaAgashe** [comment]
Hi @iSoron , Sorry for the delay.

I was of the same opinion that Controller should not have context and should be free from any Android dependency. I was actively seeking your input on how should we go about it when I created #222.

This was just meant to give an idea of what needs to be done and not to be actually merged in.
As you said I will remove context from controller and modify the constructor for exportTask and will create a new pull request with all the necessary annotations.

**Comment by iSoron** [comment]
> As you said I will remove context from controller and modify the constructor for exportTask and will create a new pull request with all the necessary annotations.

Great. Just to let you know, you don't need to create a new pull request. After you push new commits to your branch, they will automatically appear here.

**Comment by AnirudhaAgashe** [comment]
I have removed context from controller, modified export csv and db task to use application context via auto factory. Also added annotations. If anything more needs to be done let me know.

**Comment by iSoron** [comment]
Looks great now. Thank you for the patch, @AnirudhaAgashe.

**Comment by iSoron** [comment]
Hi @AnirudhaAgashe, it seems that this patch caused our automated tests to fail. See:

    https://circleci.com/gh/iSoron/uhabits/469

Could you have a look and submit another pull request to fix this?

**Comment by AnirudhaAgashe** [comment]
The testContext needs to be replaced with targetContext in tests. I will do it and submit another pull request to fix it.

**Pull request merged**
