### PR TITLE
Add "mark habit as done for today" button on details screen

### LINKED ISSUE #357: Add button to toggle checkmark in detail screen
Some notificacion guide us to the detail screen, but there are not way to check/uncheck the habbit there.

### PR DESCRIPTION
**Pull request by recheej**
Resolves #357 

It's fairly simple. I added a "mark done/undone for today" button on the details screen in OverviewCard. I check the state of the habit to see if it's been checked for the current day. Then mark it as done/undone accordingly. Once habit is checked/uncheck, I refresh the scores data as well.

image

Follow up questions for @iSoron :

1. Do you think overview card is best place to place the button? I couldn't think of a better place tbh
2. Should styling of button be changed? I'm not too sure what your styling for a "primary" button should be. let me know.

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the pull request, @recheej. I think the overview card is the best place to put this button. Regarding the style, maybe we could replace the existing `RingView` by a button similar to the checkmark widget? Here is a quick mock.

check_detail

**Comment by recheej** [comment]
@iSoron About that ring you have around the checkmark, is that an animation? Or is it an indication of your score (in screenshot it's 83% score).

**Comment by iSoron** [comment]
> About that ring you have around the checkmark, is that an animation? Or is it an indication of your score (in screenshot it's 83% score).

Sorry, it's supposed to be 83%; it's not an animation.

**Comment by iSoron** [comment]
Closing due to inactivity. If you are still working on this, please let me know and I will reopen it.

**Pull request closed without merging**
