### PR TITLE
Move PaletteColor to commonMain

### PR DESCRIPTION
**Pull request by kursadsaka**
Moves PaletteColor to commonMain for the https://github.com/iSoron/uhabits/issues/1075

### CODE REVIEW

**Comment by iSoron** [comment]
Thanks for the PR, @kursadsaka, but `PaletteColor` is already free from Java dependencies. We should also not move it to `org.isoron.platform.models`; the current package is correct.

**Comment by kursadsaka** [comment]
@iSoron I understand, but I'm asking just to be sure. There is a section in the https://github.com/iSoron/uhabits/issues/1075 for the no direct dependencies files. Should this description be changed or am I misunderstanding?

**Comment by iSoron** [comment]
@kursadsaka Moving files to `commonMain` is welcome, but the files in the "no dependencies" section can just be moved directly; there is no need to change packages, or the contents of these files. For example, `PaletteColor` should still be in `org.isoron.uhabits.core.models`. Please feel free to submit a new PR. There is also no need to submit a separate PR for each file that can be moved directly without changes; one PR for all these files would be better.

**Comment by kursadsaka** [comment]
Thhanks for the explanation @hiqua. I will come back with another PR 😁

**Pull request closed without merging**
