### PR TITLE
Export data from the statistics screen

### PR DESCRIPTION
**Pull request by JanetQC**
Hey,
solved this ticket https://github.com/iSoron/uhabits/issues/27 .
If you have any further suggestions or remarks, please let me know.

Greetings Janet

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the pull request, Janet. I will review it shortly.

**Comment by iSoron** [comment]
* The download icon seems a bit larger than the other icons we already have. Are you using Android Studio to generate them? If so, please, set the padding to 15%.
* To implement this feature, you don't need to modify ListHabitsController, ListHabitsScreen, ShowHabitActivity or ShowHabitScreen. You just need to modify ShowHabitsMenu. On ShowHabitsMenu.onItemSelected, instead of calling ShowHabitScreen.downloadHabit, you can directly create and execute the ExportCSVTask, just like we currently do in ListHabitsController. 
* If you need a reference to the habit on ShowHabitsMenu, you can modify its constructor to look like this:

        public ShowHabitsMenu(@NonNull BaseActivity activity,
                              @NonNull ShowHabitScreen screen,
                              @NonNull Habit habit)

**Comment by JanetQC** [comment]
corrected it, please review again :)

**Comment by iSoron** [comment]
Hi Janet, I have merged your pull request, after some minor changes. See 611dfa00a54518. Thank you for the patch, once again.

**Pull request closed without merging**
