### PR TITLE
Add repetition count to overview card, for #115

### PR DESCRIPTION
**Pull request by regularcoder**
Implemented this feature by counting repetitions. This means that the count won't necessarily add up with the counts shown in streaks since it ignores implicit checkmarks.

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the pull request. I will review it soon.

**Comment by iSoron** [comment]
Everything looks good. I have merged it. Thank you for the contribution.

**Comment by iSoron** [comment]
Hi @regularcoder, just to let you know, it seems your email `regularcoder@gmail.com` is not associated with your github account. If you associate it, you will appear on the [list of contributors for the project][1].

[1]: https://github.com/iSoron/uhabits/graphs/contributors

**Comment by regularcoder** [comment]
Oops, that is not my correct email address. I set it up on my local machine
long ago and forgot about it.

I will use my correct email ID for any future commits. Thanks a lot!

**Pull request merged**
