### PR TITLE
Reimplement custom frequencies

### PR DESCRIPTION
**Pull request by hiqua**
Also allow two digits for "every %d days" and only one for "every %d week".

### CODE REVIEW

**Comment by iSoron** [comment]
Looks good, thanks!

**Comment by palashkulsh** [comment]
Im not able to comprehend whether this pr breaks https://github.com/iSoron/uhabits/issues/192 ,
@hiqua request your kind help.

**Comment by hiqua** [comment]
It solves it yes.

**Comment by palashkulsh** [comment]
In current release 3 digit frequency days is not working.

**Comment by palashkulsh** [comment]
oh got it, nice catch @hiqua , really appreciate your work in this amazing foss project. Your, Isoron's and this project's contributor's work is impacting my and other user's life in a very positive way : )

I'll try building an apk for my personal use till latest apk is released. So that my habits dont break (pun intended : ))

Gentle ping to amazing @iSoron for any plans for next release

**Pull request merged**
