### PR TITLE
First day of week

### LINKED ISSUE #53: Allow user to pick Monday or Sunday as the first day of the week
The individual habit statistics would look more familiar to Europeans, if the "saturday" and "sunday" would be at the bottom and "monday" at the top (see [here](http://i.imgur.com/pwupLvL.png) for clarification). A setting, to specify the beginning of the week, could easily correct that.

The calendar view is also somehow irritating, because the months name isn't above the column, where the month actually starts, as shown in the picture above.

### PR DESCRIPTION
**Pull request by sciamano**
Fixes #53 and #74 
the first day of the week will be selected according to the current locale
PS: the history view calculations are very cryptic...

### CODE REVIEW

**Comment by iSoron** [comment]
Thank for the pull request. I will review it soon.

**Comment by iSoron** [comment]
Hi Denis, I had a look at your code. It's a good start, and it works well for most cases, but there are a couple of issues we need to fix before merging this. I am testing it with a locale that has Saturday as the first day of the week.

1. When the current day is Saturday, the leftmost column of the HabitHistoryView becomes blank. There should never be any blank columns.

2. When the history editor is open, clicking on any Saturday toggles a repetition for the Saturday of the following week. For example, clicking March 19 toggles March 26.

3. The previous issue is true with check marks added through the main screen / widgets too. A check mark on March 19 will show up in HabitHistoryView as a checkmark on March 26.

Please let me know if you can't reproduce these issues, or if you get stuck fixing them.

**Comment by sciamano** [comment]
Hi Alinson,  you are right, I can reproduce all the issues. There my second try, that will fix all of them

PS: please exclude the commit with README.md

**Comment by iSoron** [comment]
Nice, it seems to be working fine now. I have made some minor code changes and merged it into `dev`. See 24c02605. Thanks again for the pull request. This is a feature that many users asked for. Please, feel free to add youself to [the about screen](https://github.com/iSoron/uhabits/blob/f5f3ec9f88ad90df47b9cd6cb88312ceedc01d6f/app/src/main/res/layout/about.xml).

**Comment by sciamano** [comment]
thanks!

**Pull request closed without merging**
