### PR TITLE
Feature/custom first week day

### PR DESCRIPTION
**Pull request by lessmore618**
Hello Mr. Alinson Xavier, 

What a nice app. Thank you.

I thought it would be useful if users can choose which day the week starts in settings.

Another feature is to choose at which hour a new day appears, a feature I'll be working on.

If any idea, feel free to communicate it with me. I can contribute to the project in my free time.

Thank you again

### CODE REVIEW

**Comment by iSoron** [comment]
Thank you for the pull request, @lessmore618. I see that many of the changes you made are just coding conventions. For example, you changed the location of braces and you added or removed spaces. Could you please revert all of these small changes?

**Comment by OEHC** [comment]
@iSoron I have fixed this. All the changes regarding coding conventions are reverted, and the new code is also updated to follow the conventions for this project. Besides that, I have not touched or reviewed anything.
The updated code can be found here: https://github.com/OEHC/uhabits/tree/fixPR4
A compare between the fixed code, and the current dev branch is here: https://github.com/iSoron/uhabits/compare/dev...OEHC:fixPR4?expand=1

**Comment by beigirad** [comment]
hi @iSoron,
Did you want to develop or merge this pr to add the feature?
@lessmore618 does not seem to want to more developing for this project.

**Comment by iSoron** [comment]
Closing due to inactivity. If anyone wants to implement this feature, feel free to submit a new pull request.

**Pull request closed without merging**
